### ISSUE TITLE
Chat not found

### ISSUE THREAD

**Issue by sidharthb0** [sabatesduran/pibooth-telegram-upload#1]
Hello!

I’ve just installed this plugin and I’m trying to configure it. 

I’ve used **botfather** to set up a new bot and get the token_id and I’ve tried entering my chat_id both without and with a leading ‘@‘ but I’m getting an error **chat not found**. 

Uploading some screenshots for reference.

![IMG_2744](https://github.com/sabatesduran/pibooth-telegram-upload/assets/23515848/6f18aad1-ff6b-4aec-b125-7f7fc1f64422)
![IMG_2743](https://github.com/sabatesduran/pibooth-telegram-upload/assets/23515848/b4614c25-f24e-4815-8bc6-a42d9ec57a47)

**Comment by sabatesduran** [comment]
hey! how did you get the chat id? I normally create a channel with me and the bot that i created. After that use the [@JsonDumpBot](https://t.me/JsonDumpBot) forward any message from the channel to the json dump bot and use the `forward_from_chat` key to get the chat id.

I normally use channels because i want more people to see the images and they can enter it with a QR code.

**Comment by sidharthb0** [comment]
My bad, I just realised I had to use the rawDataBot to get my chat ID. Sorry for the trouble. Will try that and revert if any issues. 

Thanks!

**Comment by sidharthb0** [comment]
Linking RawDataBot here for posterity.

https://t.me/RawDataBot

For anyone using this plugin, just open up a chat with RawDataBot and hit start. The chatID in the json response is what you’ll need to place into your pibooth config file.
